export const SELECTED_PHONE = 'SELECTED_PHONE';
export const SELECTED_PHONE_SUCCESS = 'SELECTED_PHONE_SUCCESS';
export const SELECTED_PHONE_ERROR = 'SELECTED_PHONE_ERROR';
export const LIST_PHONE_REQUEST = 'LIST_PHONE_REQUEST';
export const LIST_PHONE_SUCCESS = 'LIST_PHONE_SUCCESS';
export const LIST_PHONE_ERROR = 'LIST_PHONE_ERROR';

export const SEARCH_PHONE_REQUEST = 'SEARCH_PHONE_REQUEST';
export const SEARCH_PHONE_SUCCESS = 'SEARCH_PHONE_SUCCESS';
export const SEARCH_PHONE_ERROR = 'SEARCH_PHONE_ERROR';

export const SORT_PHONE_REQUEST = 'SORT_PHONE_REQUEST';
export const SORT_PHONE_SUCCESS = 'SORT_PHONE_SUCCESS';
export const SORT_PHONE_ERROR = 'SORT_PHONE_ERROR';

